### ISSUE TITLE
Undefined symbols for Architecture arm64

### ISSUE THREAD

**Issue by caynan** [alfredh/baresip-ios#16]
Hi,

I was trying to build the latest version of `Baresip` (0.5.0), I'm also using `libre-0.5.0` and `librem-0.5.0`, and I'm getting the following error:

```
  LD      libre.dylib
  AR      libre.a
  LD      libre.dylib
  AR      libre.a
  LD      libre.dylib
  AR      libre.a
  LD      libre.dylib
  AR      libre.a
  LD      libre.dylib
  AR      libre.a
  LD      librem.dylib
ld: warning: directory not found for option '-L-lre'
Undefined symbols for architecture arm64:
  "_list_append", referenced from:
      _aubuf_append in aubuf.o
      _aumix_source_enable in aumix.o
      _vidmix_source_enable in vidmix.o
  "_list_count", referenced from:
      _aumix_source_count in aumix.o
  "_list_flush", referenced from:
      _aubuf_destructor in aubuf.o
      _aubuf_flush in aubuf.o
  "_list_unlink", referenced from:
      _auframe_destructor in aubuf.o
      _source_destructor in aumix.o
      _aumix_source_enable in aumix.o
      _source_destructor in vidmix.o
      _vidmix_source_enable in vidmix.o
  "_lock_alloc", referenced from:
      _aubuf_alloc in aubuf.o
  "_lock_read_get", referenced from:
      _aubuf_debug in aubuf.o
      _aubuf_cur_size in aubuf.o
  "_lock_rel", referenced from:
      _aubuf_append in aubuf.o
      _aubuf_read in aubuf.o
      _aubuf_get in aubuf.o
      _aubuf_flush in aubuf.o
      _aubuf_debug in aubuf.o
      _aubuf_cur_size in aubuf.o
  "_lock_write_get", referenced from:
      _aubuf_append in aubuf.o
      _aubuf_read in aubuf.o
      _aubuf_get in aubuf.o
      _aubuf_flush in aubuf.o
  "_mbuf_alloc", referenced from:
      _aubuf_write in aubuf.o
  "_mbuf_read_mem", referenced from:
      _aubuf_read in aubuf.o
  "_mbuf_write_mem", referenced from:
      _aubuf_write in aubuf.o
  "_mbuf_write_u16", referenced from:
      _autone_sine in tone.o
      _autone_dtmf in tone.o
  "_mem_alloc", referenced from:
      _aumix_thread in aumix.o
      _aumix_source_alloc in aumix.o
  "_mem_deref", referenced from:
      _aubuf_alloc in aubuf.o
      _aubuf_destructor in aubuf.o
      _aubuf_append in aubuf.o
      _auframe_destructor in aubuf.o
      _aubuf_write in aubuf.o
      _aubuf_read in aubuf.o
      _aufile_open in aufile.o
      ...
  "_mem_ref", referenced from:
      _aubuf_append in aubuf.o
      _aumix_source_alloc in aumix.o
      _vidmix_source_alloc in vidmix.o
  "_mem_zalloc", referenced from:
      _aubuf_alloc in aubuf.o
      _aubuf_append in aubuf.o
      _aufile_open in aufile.o
      _aumix_alloc in aumix.o
      _aumix_thread in aumix.o
      _aumix_source_alloc in aumix.o
      _vidmix_alloc in vidmix.o
      ...
  "_re_fprintf", referenced from:
      _wav_header_decode in wave.o
      _auconv_from_s16 in auconv.o
      _auconv_to_s16 in auconv.o
      _vidframe_draw_point in draw.o
  "_re_hprintf", referenced from:
      _aubuf_debug in aubuf.o
  "_re_printf", referenced from:
      _vidframe_init_buf in frame.o
      _vidframe_fill in frame.o
      _vidframe_copy in frame.o
      _vidconv in vconv.o
  "_sys_htoll", referenced from:
      _wav_header_encode in wave.o
  "_sys_htols", referenced from:
      _wav_header_encode in wave.o
  "_sys_ltohl", referenced from:
      _wav_header_decode in wave.o
  "_sys_ltohs", referenced from:
      _wav_header_decode in wave.o
  "_tmr_jiffies", referenced from:
      _aubuf_get in aubuf.o
      _aumix_thread in aumix.o
      _content_thread in vidmix.o
      _vidmix_thread in vidmix.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [librem.dylib] Error 1
make: *** [librem] Error 2
```
Any ideia on what might be causing this? 
I'm trying to build on my OSX Machine, running MacOS 10.11.6

Please let me know if there is any other log or information about my machine that you might need.

**Comment by apparition47** [comment]
Having the exact same issue on macOS 10.12.4/Xcode 8.3. I've tried different recent versions of libre, rem and baresip as well. Have you managed to solve the issue since?

**Comment by artur** [comment]
+1 same issue here. Anyone managed to get this working ?

**Comment by artur** [comment]
Solved here: #2

**Comment by saket424** [comment]
Edit the rem/Makefile

-       @$(LD) $(LFLAGS) $(SH_LFLAGS) $^ -L$(LIBRE_SO) -lre $(LIBS) -o $@
+       @$(LD) $(LFLAGS) $(SH_LFLAGS) $^ -L$(DESTDIR)$(LIBDIR) -lre $(LIBS) -o $@
